#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group prometheus >/dev/null; then
            addgroup --system prometheus
        fi

        if ! getent passwd prometheus >/dev/null; then
            adduser --system \
                    --ingroup prometheus \
                    --home /var/lib/prometheus \
                    --no-create-home \
                    --shell /usr/sbin/nologin \
                    prometheus
        fi

        if getent group netdev >/dev/null; then
            adduser prometheus netdev
        else
            echo "Warning: group 'netdev' not found. hostapd-exporter may fail to connect." >&2
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
