#!/bin/sh
set -e

case "$1" in
    purge)
        rm -f /etc/default/prometheus-hostapd-exporter
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-remove|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
